# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8cf79913c3db5bfad501ddbcb1c49561449e3eed16ec51ce84d7c5bb1be3238b142012a747cbd71998cdbdd79cf1c607252e4bdc5aa4f9985d32b969a0942ac
  windows_client_id:  <%= ENV["WINDOWS_CLIENT_ID"] %>
  windows_client_secret: <%= ENV["WINDOWS_CLIENT_SECRET"] %>
test:
  secret_key_base: 616b08d0c5e0d9fc930024caf5a4aa178c5504ce3c2a07c66c16ed3568679e8d56bb8cc94fa4bfebe1b8c7994efdc044e23da02be3248315ed2820370a09f76b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  windows_client_id:  <%= ENV["WINDOWS_CLIENT_ID"] %>
  windows_client_secret: <%= ENV["WINDOWS_CLIENT_SECRET"] %>
